[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cloudmesh-ai-vm"
version = "0.1.0"
description = "vm command for Cloudmesh AI"
readme = "README.md"
license = "Apache-2.0"
urls = { "Homepage" = "https://github.com/cloudmesh-ai/cloudmesh-ai-vm" }
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: System Administrators",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.10"
dependencies = [
    "cloudmesh-ai-common",
]

[project.scripts]
cmx = "cloudmesh.ai.command.vm:cmx"

[project.entry-points."cloudmesh.ai.cmc"]
vm = "cloudmesh.ai.command.vm.vm_group"
