[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cloudmesh-ai-vm"
version = "0.1.0"
description = "vm command for Cloudmesh AI"
readme = "README.md"
license = "Apache-2.0"
urls = { "Homepage" = "https://github.com/cloudmesh-ai/cloudmesh-ai-vm" }
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: System Administrators",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.10"
dependencies = [
    "cloudmesh-ai-common",
]

[project.scripts]
cmx = "cloudmesh.ai.command.vm:cmx"

[project.entry-points."cloudmesh.ai.cmc"]
vm = "cloudmesh.ai.command.vm.vm_group"

[project.entry-points."cloudmesh.ai.vm"]
multipass = "cloudmesh.ai.vm.local.MultipassManager:Provider"
lima = "cloudmesh.ai.vm.local.LimaManager:Provider"
wsl2 = "cloudmesh.ai.vm.local.Wsl2Manager:Provider"
vbox = "cloudmesh.ai.vm.local.VBoxManager:Provider"
jetstream = "cloudmesh.ai.vm.openstack.JetstreamManager:Provider"
chameleon = "cloudmesh.ai.vm.openstack.ChameleonManager:Provider"
aws = "cloudmesh.ai.vm.aws.AwsManager:Provider"
azure = "cloudmesh.ai.vm.azure.AzureManager:Provider"
google = "cloudmesh.ai.vm.google.GoogleManager:Provider"
